name: txmatching
channels:
  - conda-forge
dependencies:
  - autopep8=2.0.0
  - pip=22.3.1
  - python=3.10.5
  - pip:
    - arrow==0.17.0
    - certifi==2020.12.5
    - chardet==4.0.0
    - click==7.1.2
    - idna==2.10
    - python-dateutil==2.8.1
    - pytz==2020.5
    - requests==2.25.1
    - six==1.15.0
    - slumber==0.7.1
    - TogglPy==0.1.1
    - urllib3==1.26.5